/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingAddDTO
 */
export interface BookingAddDTO {
    /**
     * 
     * @type {Date}
     * @memberof BookingAddDTO
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof BookingAddDTO
     */
    endDate: Date;
    /**
     * 
     * @type {string}
     * @memberof BookingAddDTO
     */
    notes: string;
    /**
     * 
     * @type {string}
     * @memberof BookingAddDTO
     */
    sitterId: string;
    /**
     * 
     * @type {string}
     * @memberof BookingAddDTO
     */
    petId: string;
}

/**
 * Check if a given object implements the BookingAddDTO interface.
 */
export function instanceOfBookingAddDTO(value: object): value is BookingAddDTO {
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('notes' in value) || value['notes'] === undefined) return false;
    if (!('sitterId' in value) || value['sitterId'] === undefined) return false;
    if (!('petId' in value) || value['petId'] === undefined) return false;
    return true;
}

export function BookingAddDTOFromJSON(json: any): BookingAddDTO {
    return BookingAddDTOFromJSONTyped(json, false);
}

export function BookingAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'notes': json['notes'],
        'sitterId': json['sitterId'],
        'petId': json['petId'],
    };
}

export function BookingAddDTOToJSON(json: any): BookingAddDTO {
    return BookingAddDTOToJSONTyped(json, false);
}

export function BookingAddDTOToJSONTyped(value?: BookingAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDate': ((value['startDate']).toISOString()),
        'endDate': ((value['endDate']).toISOString()),
        'notes': value['notes'],
        'sitterId': value['sitterId'],
        'petId': value['petId'],
    };
}

