/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BookingStatusEnum = {
    Pending: 'Pending',
    Accepted: 'Accepted',
    Rejected: 'Rejected',
    Completed: 'Completed'
} as const;
export type BookingStatusEnum = typeof BookingStatusEnum[keyof typeof BookingStatusEnum];


export function instanceOfBookingStatusEnum(value: any): boolean {
    for (const key in BookingStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(BookingStatusEnum, key)) {
            if (BookingStatusEnum[key as keyof typeof BookingStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BookingStatusEnumFromJSON(json: any): BookingStatusEnum {
    return BookingStatusEnumFromJSONTyped(json, false);
}

export function BookingStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingStatusEnum {
    return json as BookingStatusEnum;
}

export function BookingStatusEnumToJSON(value?: BookingStatusEnum | null): any {
    return value as any;
}

export function BookingStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): BookingStatusEnum {
    return value as BookingStatusEnum;
}

