/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookingStatusEnum } from './BookingStatusEnum';
import {
    BookingStatusEnumFromJSON,
    BookingStatusEnumFromJSONTyped,
    BookingStatusEnumToJSON,
    BookingStatusEnumToJSONTyped,
} from './BookingStatusEnum';

/**
 * 
 * @export
 * @interface BookingUpdateDTO
 */
export interface BookingUpdateDTO {
    /**
     * 
     * @type {BookingStatusEnum}
     * @memberof BookingUpdateDTO
     */
    status?: BookingStatusEnum | null;
    /**
     * 
     * @type {Date}
     * @memberof BookingUpdateDTO
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BookingUpdateDTO
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof BookingUpdateDTO
     */
    notes?: string | null;
}



/**
 * Check if a given object implements the BookingUpdateDTO interface.
 */
export function instanceOfBookingUpdateDTO(value: object): value is BookingUpdateDTO {
    return true;
}

export function BookingUpdateDTOFromJSON(json: any): BookingUpdateDTO {
    return BookingUpdateDTOFromJSONTyped(json, false);
}

export function BookingUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : BookingStatusEnumFromJSON(json['status']),
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function BookingUpdateDTOToJSON(json: any): BookingUpdateDTO {
    return BookingUpdateDTOToJSONTyped(json, false);
}

export function BookingUpdateDTOToJSONTyped(value?: BookingUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': BookingStatusEnumToJSON(value['status']),
        'startDate': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
        'notes': value['notes'],
    };
}

