/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookingDTO } from './BookingDTO';
import {
    BookingDTOFromJSON,
    BookingDTOFromJSONTyped,
    BookingDTOToJSON,
    BookingDTOToJSONTyped,
} from './BookingDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BookingDTORequestResponse
 */
export interface BookingDTORequestResponse {
    /**
     * 
     * @type {BookingDTO}
     * @memberof BookingDTORequestResponse
     */
    readonly response?: BookingDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BookingDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the BookingDTORequestResponse interface.
 */
export function instanceOfBookingDTORequestResponse(value: object): value is BookingDTORequestResponse {
    return true;
}

export function BookingDTORequestResponseFromJSON(json: any): BookingDTORequestResponse {
    return BookingDTORequestResponseFromJSONTyped(json, false);
}

export function BookingDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : BookingDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BookingDTORequestResponseToJSON(json: any): BookingDTORequestResponse {
    return BookingDTORequestResponseToJSONTyped(json, false);
}

export function BookingDTORequestResponseToJSONTyped(value?: Omit<BookingDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

