/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ContactPreferenceEnum = {
    NoContact: 'NoContact',
    Email: 'Email',
    Phone: 'Phone'
} as const;
export type ContactPreferenceEnum = typeof ContactPreferenceEnum[keyof typeof ContactPreferenceEnum];


export function instanceOfContactPreferenceEnum(value: any): boolean {
    for (const key in ContactPreferenceEnum) {
        if (Object.prototype.hasOwnProperty.call(ContactPreferenceEnum, key)) {
            if (ContactPreferenceEnum[key as keyof typeof ContactPreferenceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ContactPreferenceEnumFromJSON(json: any): ContactPreferenceEnum {
    return ContactPreferenceEnumFromJSONTyped(json, false);
}

export function ContactPreferenceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactPreferenceEnum {
    return json as ContactPreferenceEnum;
}

export function ContactPreferenceEnumToJSON(value?: ContactPreferenceEnum | null): any {
    return value as any;
}

export function ContactPreferenceEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ContactPreferenceEnum {
    return value as ContactPreferenceEnum;
}

