/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface FeedbackAddDTO
 */
export interface FeedbackAddDTO {
    /**
     *
     * @type {number}
     * @memberof FeedbackAddDTO
     */
    rating: number;
    /**
     *
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    comment: string;
    /**
     *
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    email?: string | null;
}

/**
 * Check if a given object implements the FeedbackAddDTO interface.
 */
export function instanceOfFeedbackAddDTO(value: object): value is FeedbackAddDTO {
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function FeedbackAddDTOFromJSON(json: any): FeedbackAddDTO {
    return FeedbackAddDTOFromJSONTyped(json, false);
}

export function FeedbackAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackAddDTO {
    if (json == null) {
        return json;
    }
    return {

        'rating': json['rating'],
        'comment': json['comment'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function FeedbackAddDTOToJSON(value?: FeedbackAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'rating': value['rating'],
        'comment': value['comment'],
        'email': value['email'],
    };
}