/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FeedbackTypeEnum = {
    GeneralInquiry: 'GeneralInquiry',
    BugReport: 'BugReport',
    FeatureRequest: 'FeatureRequest',
    Compliment: 'Compliment'
} as const;
export type FeedbackTypeEnum = typeof FeedbackTypeEnum[keyof typeof FeedbackTypeEnum];


export function instanceOfFeedbackTypeEnum(value: any): boolean {
    for (const key in FeedbackTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(FeedbackTypeEnum, key)) {
            if (FeedbackTypeEnum[key as keyof typeof FeedbackTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FeedbackTypeEnumFromJSON(json: any): FeedbackTypeEnum {
    return FeedbackTypeEnumFromJSONTyped(json, false);
}

export function FeedbackTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackTypeEnum {
    return json as FeedbackTypeEnum;
}

export function FeedbackTypeEnumToJSON(value?: FeedbackTypeEnum | null): any {
    return value as any;
}

export function FeedbackTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): FeedbackTypeEnum {
    return value as FeedbackTypeEnum;
}

