/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PetAddDTO
 */
export interface PetAddDTO {
    /**
     * 
     * @type {string}
     * @memberof PetAddDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PetAddDTO
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof PetAddDTO
     */
    breed: string;
    /**
     * 
     * @type {number}
     * @memberof PetAddDTO
     */
    age: number;
}

/**
 * Check if a given object implements the PetAddDTO interface.
 */
export function instanceOfPetAddDTO(value: object): value is PetAddDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('breed' in value) || value['breed'] === undefined) return false;
    if (!('age' in value) || value['age'] === undefined) return false;
    return true;
}

export function PetAddDTOFromJSON(json: any): PetAddDTO {
    return PetAddDTOFromJSONTyped(json, false);
}

export function PetAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PetAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'breed': json['breed'],
        'age': json['age'],
    };
}

export function PetAddDTOToJSON(json: any): PetAddDTO {
    return PetAddDTOToJSONTyped(json, false);
}

export function PetAddDTOToJSONTyped(value?: PetAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'breed': value['breed'],
        'age': value['age'],
    };
}

