/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 */

import { mapValues } from '../runtime';
import type { PetDTOPagedResponse } from './PetDTOPagedResponse';
import {
    PetDTOPagedResponseFromJSON,
    PetDTOPagedResponseToJSON,
} from './PetDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageToJSON,
} from './ErrorMessage';

export interface PetDTOPagedResponseRequestResponse {
    readonly response?: PetDTOPagedResponse | null;
    readonly errorMessage?: ErrorMessage | null;
}

export function PetDTOPagedResponseRequestResponseFromJSON(json: any): PetDTOPagedResponseRequestResponse {
    return PetDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function PetDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PetDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        'response': json['response'] == null ? undefined : PetDTOPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function PetDTOPagedResponseRequestResponseToJSON(value?: Omit<PetDTOPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {};
}