/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PetDTO } from './PetDTO';
import {
    PetDTOFromJSON,
    PetDTOFromJSONTyped,
    PetDTOToJSON,
    PetDTOToJSONTyped,
} from './PetDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface PetDTOListRequestResponse
 */
export interface PetDTOListRequestResponse {
    /**
     * 
     * @type {Array<PetDTO>}
     * @memberof PetDTOListRequestResponse
     */
    readonly response?: Array<PetDTO> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof PetDTOListRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the PetDTOListRequestResponse interface.
 */
export function instanceOfPetDTOListRequestResponse(value: object): value is PetDTOListRequestResponse {
    return true;
}

export function PetDTOListRequestResponseFromJSON(json: any): PetDTOListRequestResponse {
    return PetDTOListRequestResponseFromJSONTyped(json, false);
}

export function PetDTOListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PetDTOListRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ((json['response'] as Array<any>).map(PetDTOFromJSON)),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function PetDTOListRequestResponseToJSON(json: any): PetDTOListRequestResponse {
    return PetDTOListRequestResponseToJSONTyped(json, false);
}

export function PetDTOListRequestResponseToJSONTyped(value?: Omit<PetDTOListRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

