/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PetDTO } from './PetDTO';
import {
    PetDTOFromJSON,
    PetDTOFromJSONTyped,
    PetDTOToJSON,
    PetDTOToJSONTyped,
} from './PetDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface PetDTORequestResponse
 */
export interface PetDTORequestResponse {
    /**
     * 
     * @type {PetDTO}
     * @memberof PetDTORequestResponse
     */
    readonly response?: PetDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof PetDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the PetDTORequestResponse interface.
 */
export function instanceOfPetDTORequestResponse(value: object): value is PetDTORequestResponse {
    return true;
}

export function PetDTORequestResponseFromJSON(json: any): PetDTORequestResponse {
    return PetDTORequestResponseFromJSONTyped(json, false);
}

export function PetDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PetDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : PetDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function PetDTORequestResponseToJSON(json: any): PetDTORequestResponse {
    return PetDTORequestResponseToJSONTyped(json, false);
}

export function PetDTORequestResponseToJSONTyped(value?: Omit<PetDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

