/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 */

import { mapValues } from '../runtime';
import type { PetDTO } from './PetDTO';
import {
    PetDTOFromJSON,
    PetDTOToJSON,
} from './PetDTO';

export interface PetDTOPagedResponse {
    page?: number;
    pageSize?: number;
    totalCount?: number;
    data?: Array<PetDTO> | null;
}

export function PetDTOPagedResponseFromJSON(json: any): PetDTOPagedResponse {
    return PetDTOPagedResponseFromJSONTyped(json, false);
}

export function PetDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PetDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PetDTOFromJSON)),
    };
}

export function PetDTOPagedResponseToJSON(value?: PetDTOPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PetDTOToJSON)),
    };
}