/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PetUpdateDTO
 */
export interface PetUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof PetUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PetUpdateDTO
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PetUpdateDTO
     */
    breed?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PetUpdateDTO
     */
    age?: number | null;
}

/**
 * Check if a given object implements the PetUpdateDTO interface.
 */
export function instanceOfPetUpdateDTO(value: object): value is PetUpdateDTO {
    return true;
}

export function PetUpdateDTOFromJSON(json: any): PetUpdateDTO {
    return PetUpdateDTOFromJSONTyped(json, false);
}

export function PetUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PetUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'breed': json['breed'] == null ? undefined : json['breed'],
        'age': json['age'] == null ? undefined : json['age'],
    };
}

export function PetUpdateDTOToJSON(json: any): PetUpdateDTO {
    return PetUpdateDTOToJSONTyped(json, false);
}

export function PetUpdateDTOToJSONTyped(value?: PetUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'breed': value['breed'],
        'age': value['age'],
    };
}

