/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewDTO } from './ReviewDTO';
import {
    ReviewDTOFromJSON,
    ReviewDTOFromJSONTyped,
    ReviewDTOToJSON,
    ReviewDTOToJSONTyped,
} from './ReviewDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ReviewDTOListRequestResponse
 */
export interface ReviewDTOListRequestResponse {
    /**
     * 
     * @type {Array<ReviewDTO>}
     * @memberof ReviewDTOListRequestResponse
     */
    readonly response?: Array<ReviewDTO> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ReviewDTOListRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the ReviewDTOListRequestResponse interface.
 */
export function instanceOfReviewDTOListRequestResponse(value: object): value is ReviewDTOListRequestResponse {
    return true;
}

export function ReviewDTOListRequestResponseFromJSON(json: any): ReviewDTOListRequestResponse {
    return ReviewDTOListRequestResponseFromJSONTyped(json, false);
}

export function ReviewDTOListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewDTOListRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ((json['response'] as Array<any>).map(ReviewDTOFromJSON)),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ReviewDTOListRequestResponseToJSON(json: any): ReviewDTOListRequestResponse {
    return ReviewDTOListRequestResponseToJSONTyped(json, false);
}

export function ReviewDTOListRequestResponseToJSONTyped(value?: Omit<ReviewDTOListRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

