/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewDTO } from './ReviewDTO';
import {
    ReviewDTOFromJSON,
    ReviewDTOFromJSONTyped,
    ReviewDTOToJSON,
    ReviewDTOToJSONTyped,
} from './ReviewDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ReviewDTORequestResponse
 */
export interface ReviewDTORequestResponse {
    /**
     * 
     * @type {ReviewDTO}
     * @memberof ReviewDTORequestResponse
     */
    readonly response?: ReviewDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ReviewDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the ReviewDTORequestResponse interface.
 */
export function instanceOfReviewDTORequestResponse(value: object): value is ReviewDTORequestResponse {
    return true;
}

export function ReviewDTORequestResponseFromJSON(json: any): ReviewDTORequestResponse {
    return ReviewDTORequestResponseFromJSONTyped(json, false);
}

export function ReviewDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ReviewDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ReviewDTORequestResponseToJSON(json: any): ReviewDTORequestResponse {
    return ReviewDTORequestResponseToJSONTyped(json, false);
}

export function ReviewDTORequestResponseToJSONTyped(value?: Omit<ReviewDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

