/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewAddDTO
 */
export interface ReviewAddDTO {
    /**
     * 
     * @type {number}
     * @memberof ReviewAddDTO
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewAddDTO
     */
    comment: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewAddDTO
     */
    sitterId: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewAddDTO
     */
    bookingId: string;
}

/**
 * Check if a given object implements the ReviewAddDTO interface.
 */
export function instanceOfReviewAddDTO(value: object): value is ReviewAddDTO {
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('sitterId' in value) || value['sitterId'] === undefined) return false;
    if (!('bookingId' in value) || value['bookingId'] === undefined) return false;
    return true;
}

export function ReviewAddDTOFromJSON(json: any): ReviewAddDTO {
    return ReviewAddDTOFromJSONTyped(json, false);
}

export function ReviewAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'rating': json['rating'],
        'comment': json['comment'],
        'sitterId': json['sitterId'],
        'bookingId': json['bookingId'],
    };
}

export function ReviewAddDTOToJSON(json: any): ReviewAddDTO {
    return ReviewAddDTOToJSONTyped(json, false);
}

export function ReviewAddDTOToJSONTyped(value?: ReviewAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating': value['rating'],
        'comment': value['comment'],
        'sitterId': value['sitterId'],
        'bookingId': value['bookingId'],
    };
}

