/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewUpdateDTO
 */
export interface ReviewUpdateDTO {
    /**
     * 
     * @type {number}
     * @memberof ReviewUpdateDTO
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewUpdateDTO
     */
    comment?: string | null;
}

/**
 * Check if a given object implements the ReviewUpdateDTO interface.
 */
export function instanceOfReviewUpdateDTO(value: object): value is ReviewUpdateDTO {
    if (!('rating' in value) || value['rating'] === undefined) return false;
    return true;
}

export function ReviewUpdateDTOFromJSON(json: any): ReviewUpdateDTO {
    return ReviewUpdateDTOFromJSONTyped(json, false);
}

export function ReviewUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'rating': json['rating'],
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function ReviewUpdateDTOToJSON(json: any): ReviewUpdateDTO {
    return ReviewUpdateDTOToJSONTyped(json, false);
}

export function ReviewUpdateDTOToJSONTyped(value?: ReviewUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating': value['rating'],
        'comment': value['comment'],
    };
}

