/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SitterProfileAddDTO
 */
export interface SitterProfileAddDTO {
    /**
     * 
     * @type {string}
     * @memberof SitterProfileAddDTO
     */
    bio: string;
    /**
     * 
     * @type {number}
     * @memberof SitterProfileAddDTO
     */
    yearsExperience: number;
    /**
     * 
     * @type {number}
     * @memberof SitterProfileAddDTO
     */
    hourlyRate: number;
    /**
     * 
     * @type {string}
     * @memberof SitterProfileAddDTO
     */
    location: string;
}

/**
 * Check if a given object implements the SitterProfileAddDTO interface.
 */
export function instanceOfSitterProfileAddDTO(value: object): value is SitterProfileAddDTO {
    if (!('bio' in value) || value['bio'] === undefined) return false;
    if (!('yearsExperience' in value) || value['yearsExperience'] === undefined) return false;
    if (!('hourlyRate' in value) || value['hourlyRate'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function SitterProfileAddDTOFromJSON(json: any): SitterProfileAddDTO {
    return SitterProfileAddDTOFromJSONTyped(json, false);
}

export function SitterProfileAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitterProfileAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'bio': json['bio'],
        'yearsExperience': json['yearsExperience'],
        'hourlyRate': json['hourlyRate'],
        'location': json['location'],
    };
}

export function SitterProfileAddDTOToJSON(json: any): SitterProfileAddDTO {
    return SitterProfileAddDTOToJSONTyped(json, false);
}

export function SitterProfileAddDTOToJSONTyped(value?: SitterProfileAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bio': value['bio'],
        'yearsExperience': value['yearsExperience'],
        'hourlyRate': value['hourlyRate'],
        'location': value['location'],
    };
}

