/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SitterProfileDTO
 */
export interface SitterProfileDTO {
    /**
     * 
     * @type {string}
     * @memberof SitterProfileDTO
     */
    bio: string;
    /**
     * 
     * @type {number}
     * @memberof SitterProfileDTO
     */
    yearsExperience: number;
    /**
     * 
     * @type {number}
     * @memberof SitterProfileDTO
     */
    hourlyRate: number;
    /**
     * 
     * @type {string}
     * @memberof SitterProfileDTO
     */
    location: string;
}

/**
 * Check if a given object implements the SitterProfileDTO interface.
 */
export function instanceOfSitterProfileDTO(value: object): value is SitterProfileDTO {
    if (!('bio' in value) || value['bio'] === undefined) return false;
    if (!('yearsExperience' in value) || value['yearsExperience'] === undefined) return false;
    if (!('hourlyRate' in value) || value['hourlyRate'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function SitterProfileDTOFromJSON(json: any): SitterProfileDTO {
    return SitterProfileDTOFromJSONTyped(json, false);
}

export function SitterProfileDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitterProfileDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'bio': json['bio'],
        'yearsExperience': json['yearsExperience'],
        'hourlyRate': json['hourlyRate'],
        'location': json['location'],
    };
}

export function SitterProfileDTOToJSON(json: any): SitterProfileDTO {
    return SitterProfileDTOToJSONTyped(json, false);
}

export function SitterProfileDTOToJSONTyped(value?: SitterProfileDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bio': value['bio'],
        'yearsExperience': value['yearsExperience'],
        'hourlyRate': value['hourlyRate'],
        'location': value['location'],
    };
}

