/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SitterProfileUpdateDTO
 */
export interface SitterProfileUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof SitterProfileUpdateDTO
     */
    bio?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SitterProfileUpdateDTO
     */
    yearsExperience?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SitterProfileUpdateDTO
     */
    hourlyRate?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SitterProfileUpdateDTO
     */
    location?: string | null;
}

/**
 * Check if a given object implements the SitterProfileUpdateDTO interface.
 */
export function instanceOfSitterProfileUpdateDTO(value: object): value is SitterProfileUpdateDTO {
    return true;
}

export function SitterProfileUpdateDTOFromJSON(json: any): SitterProfileUpdateDTO {
    return SitterProfileUpdateDTOFromJSONTyped(json, false);
}

export function SitterProfileUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitterProfileUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'bio': json['bio'] == null ? undefined : json['bio'],
        'yearsExperience': json['yearsExperience'] == null ? undefined : json['yearsExperience'],
        'hourlyRate': json['hourlyRate'] == null ? undefined : json['hourlyRate'],
        'location': json['location'] == null ? undefined : json['location'],
    };
}

export function SitterProfileUpdateDTOToJSON(json: any): SitterProfileUpdateDTO {
    return SitterProfileUpdateDTOToJSONTyped(json, false);
}

export function SitterProfileUpdateDTOToJSONTyped(value?: SitterProfileUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bio': value['bio'],
        'yearsExperience': value['yearsExperience'],
        'hourlyRate': value['hourlyRate'],
        'location': value['location'],
    };
}

