/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface StringRequestResponse
 */
export interface StringRequestResponse {
    /**
     * 
     * @type {string}
     * @memberof StringRequestResponse
     */
    readonly response?: string | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof StringRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the StringRequestResponse interface.
 */
export function instanceOfStringRequestResponse(value: object): value is StringRequestResponse {
    return true;
}

export function StringRequestResponseFromJSON(json: any): StringRequestResponse {
    return StringRequestResponseFromJSONTyped(json, false);
}

export function StringRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StringRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : json['response'],
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function StringRequestResponseToJSON(json: any): StringRequestResponse {
    return StringRequestResponseToJSONTyped(json, false);
}

export function StringRequestResponseToJSONTyped(value?: Omit<StringRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

