/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface UserDTOListRequestResponse
 */
export interface UserDTOListRequestResponse {
    /**
     * 
     * @type {Array<UserDTO>}
     * @memberof UserDTOListRequestResponse
     */
    readonly response?: Array<UserDTO> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof UserDTOListRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the UserDTOListRequestResponse interface.
 */
export function instanceOfUserDTOListRequestResponse(value: object): value is UserDTOListRequestResponse {
    return true;
}

export function UserDTOListRequestResponseFromJSON(json: any): UserDTOListRequestResponse {
    return UserDTOListRequestResponseFromJSONTyped(json, false);
}

export function UserDTOListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTOListRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ((json['response'] as Array<any>).map(UserDTOFromJSON)),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function UserDTOListRequestResponseToJSON(json: any): UserDTOListRequestResponse {
    return UserDTOListRequestResponseToJSONTyped(json, false);
}

export function UserDTOListRequestResponseToJSONTyped(value?: Omit<UserDTOListRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

